StudentInfoManagementSystem/Controllers/ApplicationDashboardController.cs
using StudentInfoManagementSystem.Data;
using StudentInfoManagementSystem.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudentInfoManagementSystem.Controllers
{
	[Authorize]
    public class ApplicationDashboardController : Controller
    {
		StudentApplicationDbContext db = new StudentApplicationDbContext();
		public ActionResult Dashboard()
		{
			var students = db.students.ToList();
			int totalStudents = students.Count();

			var addressWiseStudentsCount = students.GroupBy(s => s.HomeAddress).ToDictionary(s => s.Key, s => s.Count());

			var viewModel = new ApplicationDashboard
			{
				TotalNumberOfStudents = totalStudents,
				AddressWiseStudentsCount = addressWiseStudentsCount
			};

			return View(viewModel);
		}
	}
}

StudentInfoManagementSystem/Controllers/StudentsController.cs
using PagedList;
using StudentInfoManagementSystem.DAL;
using StudentInfoManagementSystem.Data;
using StudentInfoManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudentInfoManagementSystem.Controllers
{
	[Authorize]
	public class StudentsController : Controller
	{
		StudentApplicationDbContext db = new StudentApplicationDbContext();
		private IStudentRepository studentRepository;
		public StudentsController()
		{
			this.studentRepository = new StudentRepository(new StudentApplicationDbContext());
		}

		public StudentsController(IStudentRepository studentRepository)
		{
			this.studentRepository = studentRepository;
		}

		
		public ActionResult Index(string searchString, string sortOrder,int? page, string currentFilter)
		{
			ViewBag.CurrentSort = sortOrder;
			ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
			if (searchString != null)
			{
				page = 1;
			}
			else
			{
				searchString = currentFilter;
			}

			ViewBag.CurrentFilter = searchString;

			//var students = from s in studentRepository.GetAll()
			//			   where !s.IsDeleted
			//			   select s;                              

			var students = db.GetStudentsFromStoredProcedure();


			if (!String.IsNullOrEmpty(searchString))
			{
				searchString = searchString.ToUpper();

				students = students.Where(s =>                                      
					s.StudentName.ToUpper().Contains(searchString) ||
					s.HomeAddress.ToUpper().Contains(searchString) ||
					s.RegistrationDate.ToString("yyyy-MM-dd").Contains(searchString)
				);
			}

			students = students.OrderBy(s => s.RegistrationDate);        

			switch (sortOrder)             
			{
				case "name_desc":
					students = students.OrderByDescending(s => s.StudentName);
					break;
				default:
					students = students.OrderBy(s => s.StudentName);
					break;
			}
			int pageSize = 3;
			int pageNumber = (page ?? 1);
			return View(students.ToPagedList(pageNumber, pageSize));

		}


		[HttpGet]
		public ActionResult Create()
		{
			return View();
		}


		[HttpPost]
		public ActionResult Create(Student student, HttpPostedFileBase profileImage)
		{
			try
			{ 
				if (ModelState.IsValid) 
				{

					if (profileImage != null && profileImage.ContentLength > 0)
					{
						string fileName = Path.GetFileName(profileImage.FileName);
						string path = Path.Combine(Server.MapPath("~/Images/"), fileName);
						profileImage.SaveAs(path);
						student.ProfileImage = "/Images/" + fileName;
					}


					studentRepository.AddStudent(student);    
					studentRepository.Save();
					return RedirectToAction("Index");
				}
			}
			catch (SqlException)
			{
				ModelState.AddModelError("", "Please pass the correct data");
			}
			return View(student);
		}


		[HttpGet]
		public ViewResult Details(int id)
		{
			Student student = studentRepository.GetStudentById(id);
			return View(student);
		}


		[HttpGet]
		public ActionResult Edit(int id)
		{
			Student student = studentRepository.GetStudentById(id);
			return View(student);
		}


		[HttpPost]
		public ActionResult Edit(Student updatedStudent)
		{
			try
			{
				if (ModelState.IsValid)
				{
					Student existingStudent = studentRepository.GetStudentById(updatedStudent.StudentId);

					existingStudent.StudentName = updatedStudent.StudentName;
					existingStudent.FatherName = updatedStudent.FatherName;
					existingStudent.MotherName = updatedStudent.MotherName;
					existingStudent.Age = updatedStudent.Age;
					existingStudent.HomeAddress = updatedStudent.HomeAddress;

					studentRepository.UpdateStudent(existingStudent);
					studentRepository.Save();

					return RedirectToAction("Index");
				}
			}
			catch (SqlException)
			{
				ModelState.AddModelError("", "Please pass the correct data");
			}
			return View(updatedStudent);
		}
		//[HttpPost]
		//public ActionResult Edit(Student updatedStudent, HttpPostedFileBase profileImage)
		//{
		//	try
		//	{
		//		if (ModelState.IsValid)
		//		{
		//			Student existingStudent = studentRepository.GetStudentById(updatedStudent.StudentId);

		//			// Update student properties
		//			existingStudent.StudentName = updatedStudent.StudentName;
		//			existingStudent.FatherName = updatedStudent.FatherName;
		//			existingStudent.MotherName = updatedStudent.MotherName;
		//			existingStudent.Age = updatedStudent.Age;
		//			existingStudent.HomeAddress = updatedStudent.HomeAddress;

		//			// Check if a new profile image was uploaded
		//			if (profileImage != null && profileImage.ContentLength > 0)
		//			{
		//				string fileName = Path.GetFileName(profileImage.FileName);
		//				string path = Path.Combine(Server.MapPath("~/Images/"), fileName);
		//				profileImage.SaveAs(path);
		//				existingStudent.ProfileImage = "/Images/" + fileName;
		//			}

		//			studentRepository.UpdateStudent(existingStudent);
		//			studentRepository.Save();

		//			return RedirectToAction("Index");
		//		}
		//	}
		//	catch (SqlException)
		//	{
		//		ModelState.AddModelError("", "Please pass the correct data");
		//	}

		//	return View(updatedStudent);
		//}


		[HttpGet]
		public ActionResult Delete(bool? saveChangesError = false, int id = 0)
		{
			if (saveChangesError.GetValueOrDefault())
			{
				ViewBag.ErrorMessage = "Delete failed";
			}
			Student student = studentRepository.GetStudentById(id);       
			return View(student);         
		}

		[HttpPost]                          
		public ActionResult Delete(int id)
		{
			try
			{
				if (ModelState.IsValid)
				{
					studentRepository.SoftDeleteStudent(id);
					studentRepository.Save();
				}
			}
			catch (SqlException)
			{
				ModelState.AddModelError("", "Please pass the correct data");   
			}
			return RedirectToAction("Index");     
		}


	}
}

StudentInfoManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Student Info Project</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="@Url.Action("Index", "Home")">Technossus Machine Test</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Student Information Portal", "Index", "Students", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Dashboard", "Dashboard", "ApplicationDashboard", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <span class="nav-link">Dear, @User.Identity.Name</span>
                            </li>
                            <li class="nav-item">
                                @Html.ActionLink("Logout", "Logout", "Account", null, new { @class = "nav-link" })
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                @Html.ActionLink("Login", "Login", "Account", null, new { @class = "nav-link" })
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <main class="container mt-4">
        @RenderBody()
    </main>

    <footer class="bg-dark text-light text-center py-3">
        &copy; @DateTime.Now.Year Made By Girish
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>